### ISSUE TITLE
Missing assets/pandoc.exe

### ISSUE THREAD

**Issue by TienDatDieu** [vertexi/tex2mathml#1]
Hi @vertexi , I have tried your program and it was fine until I click the conver copy. It said missing the pandoc.exe. Could you please check it?

**Comment by vertexi** [comment]
Sorry for the late response, I can't reproduce the error in a brand new virtual machine. Can you give me some detail info? (such as a screenshot)

**Comment by TienDatDieu** [comment]
Hi @vertexi, Sorry but I did not have pandoc.exe in my machine so it did not work. I will close the comment.
